services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: nestjs_webzio_db
      POSTGRES_USER: nestjs_webzio_user
      POSTGRES_PASSWORD: nestjs_webzio_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: nestjs_webzio_user
      DB_PASSWORD: nestjs_webzio_password
      DB_NAME: nestjs_webzio_db
      WEBZIO_API_KEY: 3eb4d06f-315a-4481-b357-616444fc4e73
    restart: always
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
    driver: local