export enum WebzioNewsSortBy {
  RELEVANCY = 'relevancy',
  SOCIAL_FACEBOOK_LIKES = 'social.facebook.likes',
  SOCIAL_FACEBOOK_SHARES = 'social.facebook.shares',
  SOCIAL_FACEBOOK_COMMENTS = 'social.facebook.comments',
  SOCIAL_GPLUS_SHARES = 'social.gplus.shares',
  SOCIAL_PINTEREST_SHARES = 'social.pinterest.shares',
  SOCIAL_LINKEDIN_SHARES = 'social.linkedin.shares',
  SOCIAL_STUMBLEDUPON_SHARES = 'social.stumbledupon.shares',
  SOCIAL_VK_SHARES = 'social.vk.shares',
  REPLIES_COUNT = 'replies_count',
  PARTICIPANTS_COUNT = 'participants_count',
  PERFORMANCE_SCORE = 'performance_score',
  PUBLISHED = 'published',
  THREAD_PUBLISHED = 'thread.published',
  DOMAIN_RANK = 'domain_rank',
  ORD_IN_THREAD = 'ord_in_thread',
  RATING = 'rating',
}
